version: "2"

services:
  caliper_2.1:
    container_name: caliper_2.1
    image: hyperledger/caliper:0.4.1
    command: launch manager --caliper-fabric-gateway-enabled
    environment:
      - CALIPER_BIND_SUT=fabric:2.1.0
      - CALIPER_BENCHCONFIG=benchmarks/scenario/simple/Ankit-Fabric_v2.1/config.yaml
      - CALIPER_NETWORKCONFIG=networks/fabric/Ankit-Fabric_v2.1/network-config_2.1.yaml
    volumes:
      - ./Performance-analysis-project:/hyperledger/caliper/workspace
    network_mode: host
